# Generated by Django 5.2.8 on 2025-11-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVImporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('year', models.CharField(blank=True, max_length=50)),
                ('tv_certificate', models.CharField(blank=True, max_length=10)),
                ('duration_per_episode', models.CharField(blank=True, max_length=20)),
                ('genre', models.CharField(blank=True, max_length=255)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('actors', models.TextField(blank=True)),
                ('votes', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
