# Generated by Django 5.2.8 on 2025-11-16 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvimporter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvimporter',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
